spring.application.name=ollamarestapi
spring.ai.ollama.chat.model=mistral

jira.username=opeyemi.olugunojin@sterling.ng
jira.apiToken=ATATT3xFfGF0S9g37iKMywIHDmir8URSuf2Llky9bA6CUY-jj7ErkUXFXLt4U56aayDyZJj4fqVpEr3Uzi8U92x-u9E8Z06wvnj7DcPYq30GgCEAWJuMkKz9c5Y5NdxdPH0gU_Iq25rgHQ_q1LHncM5i39TtAEIGJIoyQi5HnHQubJcjMgIPiJs=E9ACDD84
jira.apiUrl=https://sterlingbank.atlassian.net/

server.port=8081


